apiVersion: v1
kind: Service
metadata:
  name: recommendation-v2
  labels:
    app: recommendation  
    version: v2
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: recommendation
    version: v2
